"""
This is a dummy recipe which stores a "label" (text string).
It's meant to be a specification of where the material came from.
For example, the "lattice decoration" materials in C2DB are labelled
as coming from "lattice decoration".
"""

from asr.core import command, option, ASRResult, DictStr



def webpanel(result, row, key_descriptions):
    from asr.database.browser import table, describe_entry, href
    lyngby22_description = """\
    Structures generated by CDVAE.  <Description>

    Ref.: <publication>
    """

    descriptions = {
        'potato': f"hello world {href('link', 'https://example.com')}",
        'Lyngby22_CDVAE': lyngby22_description,
    }

    label = result.get('label')
    if label in descriptions:
        label = describe_entry(label, descriptions[label])
    if label is None:
        return []  # No panels generated

    hello = describe_entry('Material label', label_explanation)

    panel = {
        'title': 'Summary',
        'columns': [[{
            'type': 'table',
            'rows': [[hello, label]],
            'columnwidth': 4,
        }]],
    }
    return [panel]


label_explanation = (
    'Label specifying generation procedure or origin of material')


class LabelResult(ASRResult):
    label: str
    key_descriptions = {'label': label_explanation}
    formats = {'ase_webpanel': webpanel}


@command(module='asr.utils.labels',
         returns=LabelResult)
@option('--label', help=label_explanation, type=str)
def main(label):
    return LabelResult.fromdata(label=label)


if __name__ == '__main__':
    main.cli()
